### ISSUE TITLE
README

### ISSUE THREAD

**Issue by zipzit** [vimsos/unity-scene-handling#2]
Possible to get a bit of help here?  I'm totally not understanding what's in the proposed script files.  Its not clear on how to propagate the array which holds all the scene levels, never mind triggers to change levels/scenes.  Possible to get an example of the GameManager (MonoBehaviour) script and SceneLevel (SceneRoot) script so I understand?  Or idiot's guide instructions on how to use the contents within the test folder?  

I'm thinking the hello world version of "Unity-Scene-Handling"  Create scene1, create scene2, load scene1, push the "S" key, flip to scene2 (nevermind the player 'values' that need to go along for the ride...)

I'm grateful for the work, just can't figure out how to use it...   many thanks for sharing your work open source...

**Comment by vimsos** [comment]
> Possible to get a bit of help here?

Sure

>  I'm totally not understanding what's in the proposed script files. Its not clear on how to propagate the array which holds all the scene levels, never mind triggers to change levels/scenes. 

It is not necessary to propagate the array containing the levels to the other scenes, it will remain in scope as long as the scene containing the `GameManager` is loaded. In that example I am trying to show how a user of this package could extend the `SceneRoot` class to implement such a trigger. The `PuzzleScene` class inherits from `SceneRoot` and exposes the `Finished` boolean property. This property would be set according to the game logic (inside the `PuzzleScene` class) after the player had successfully finished the puzzle. The `GameManager` would wait until the `Finished` evaluates to true and then it would unload the puzzle scene.

> Possible to get an example of the GameManager (MonoBehaviour) script and SceneLevel (SceneRoot) script so I understand? Or idiot's guide instructions on how to use the contents within the test folder?

The contents of the test folder are to be used while developing this package, to test its behavior and if it is loading the scenes and their payloads correctly.

I guess the README and the provided example are not very clear on how this package is supposed to be used so I'm going to have to come up with a better example.
